# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet(" *{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    background: transparent;\n"
"    padding:0;\n"
"    margin:0;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color:#1f232a;\n"
"}\n"
"\n"
"#leftMenuSubContainer{\n"
"  background-color:#16191d;\n"
"}\n"
"#leftMenuSubContainer QPushButton{\n"
"  text-align: left;\n"
"  padding:5px 10px; \n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"\n"
"}\n"
"\n"
"#centerMenuSubContainer,#rightMenuSubContainer{\n"
"    background-color:#2c313c;\n"
"}\n"
"\n"
"#frame_4,#frame_8,#popupNotificationSubContainer{\n"
"    background-color:#16191d;\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"#headerContiner{\n"
"    background-color:#2c313c;\n"
"}\n"
"\n"
"#frame_29{\n"
"    background-color:#ffffff;\n"
"\n"
"}\n"
"#mainbodyContent{\n"
"    background-color: #fff;\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuContainer = QCustomSlideMenu(self.centralwidget)
        self.leftMenuContainer.setMinimumSize(QtCore.QSize(90, 0))
        self.leftMenuContainer.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leftMenuContainer.setStyleSheet("")
        self.leftMenuContainer.setObjectName("leftMenuContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenuContainer)
        self.verticalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.leftMenuSubContainer = QtWidgets.QWidget(self.leftMenuContainer)
        self.leftMenuSubContainer.setObjectName("leftMenuSubContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftMenuSubContainer)
        self.verticalLayout.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.leftMenuSubContainer)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuBtn = QtWidgets.QPushButton(self.frame)
        self.menuBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Images/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBtn.setIcon(icon)
        self.menuBtn.setIconSize(QtCore.QSize(70, 70))
        self.menuBtn.setObjectName("menuBtn")
        self.horizontalLayout_2.addWidget(self.menuBtn)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.leftMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeBtn = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.homeBtn.setFont(font)
        self.homeBtn.setStyleSheet("background-color: #1f232a")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Images/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon1)
        self.homeBtn.setIconSize(QtCore.QSize(70, 70))
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_3.addWidget(self.homeBtn)
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.dataBtn = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dataBtn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Images/icons/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataBtn.setIcon(icon2)
        self.dataBtn.setIconSize(QtCore.QSize(70, 70))
        self.dataBtn.setObjectName("dataBtn")
        self.verticalLayout_3.addWidget(self.dataBtn)
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(self.leftMenuSubContainer)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.leftMenuSubContainer, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.leftMenuContainer)
        self.centerMenuContainer = QCustomSlideMenu(self.centralwidget)
        self.centerMenuContainer.setEnabled(True)
        self.centerMenuContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.centerMenuContainer.setMaximumSize(QtCore.QSize(0, 16777215))
        self.centerMenuContainer.setObjectName("centerMenuContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centerMenuContainer)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.centerMenuSubContainer = QtWidgets.QWidget(self.centerMenuContainer)
        self.centerMenuSubContainer.setMinimumSize(QtCore.QSize(350, 0))
        self.centerMenuSubContainer.setObjectName("centerMenuSubContainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centerMenuSubContainer)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.centerMenuSubContainer)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.closeCenterMenuBtn = QtWidgets.QPushButton(self.frame_4)
        self.closeCenterMenuBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Images/icons/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeCenterMenuBtn.setIcon(icon3)
        self.closeCenterMenuBtn.setIconSize(QtCore.QSize(40, 40))
        self.closeCenterMenuBtn.setObjectName("closeCenterMenuBtn")
        self.horizontalLayout_3.addWidget(self.closeCenterMenuBtn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.centerMenuPages = QCustomStackedWidget(self.centerMenuSubContainer)
        self.centerMenuPages.setStyleSheet("")
        self.centerMenuPages.setObjectName("centerMenuPages")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.centerMenuPages.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.centerMenuPages.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_9.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setMinimumSize(QtCore.QSize(300, 100))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.textBrowser = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 600))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_9.addWidget(self.textBrowser)
        self.centerMenuPages.addWidget(self.page_3)
        self.verticalLayout_6.addWidget(self.centerMenuPages)
        self.verticalLayout_5.addWidget(self.centerMenuSubContainer, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.centerMenuContainer)
        self.mainBodyContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContainer.sizePolicy().hasHeightForWidth())
        self.mainBodyContainer.setSizePolicy(sizePolicy)
        self.mainBodyContainer.setStyleSheet("")
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mainBodyContainer)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.headerContiner = QtWidgets.QWidget(self.mainBodyContainer)
        self.headerContiner.setMaximumSize(QtCore.QSize(16715, 16777215))
        self.headerContiner.setObjectName("headerContiner")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.headerContiner)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.headerContiner)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.horizontalLayout_4.addWidget(self.frame_5, 0, QtCore.Qt.AlignLeft)
        self.frame_6 = QtWidgets.QFrame(self.headerContiner)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(30)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4.addWidget(self.frame_6, 0, QtCore.Qt.AlignHCenter)
        self.frame_7 = QtWidgets.QFrame(self.headerContiner)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_5.setSpacing(30)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.minimizeBtn = QtWidgets.QPushButton(self.frame_7)
        self.minimizeBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Images/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeBtn.setIcon(icon4)
        self.minimizeBtn.setIconSize(QtCore.QSize(60, 60))
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.horizontalLayout_5.addWidget(self.minimizeBtn)
        self.restoreBtn = QtWidgets.QPushButton(self.frame_7)
        self.restoreBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Images/icons/square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreBtn.setIcon(icon5)
        self.restoreBtn.setIconSize(QtCore.QSize(60, 60))
        self.restoreBtn.setObjectName("restoreBtn")
        self.horizontalLayout_5.addWidget(self.restoreBtn)
        self.closeBtn = QtWidgets.QPushButton(self.frame_7)
        self.closeBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Images/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon6)
        self.closeBtn.setIconSize(QtCore.QSize(60, 60))
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_5.addWidget(self.closeBtn)
        self.horizontalLayout_4.addWidget(self.frame_7, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.headerContiner)
        self.mainbodyContent = QtWidgets.QWidget(self.mainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainbodyContent.sizePolicy().hasHeightForWidth())
        self.mainbodyContent.setSizePolicy(sizePolicy)
        self.mainbodyContent.setMinimumSize(QtCore.QSize(688, 198))
        self.mainbodyContent.setObjectName("mainbodyContent")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.mainbodyContent)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mainContentsContainer = QtWidgets.QWidget(self.mainbodyContent)
        self.mainContentsContainer.setObjectName("mainContentsContainer")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.mainContentsContainer)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.mainPages = QCustomStackedWidget(self.mainContentsContainer)
        self.mainPages.setObjectName("mainPages")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_11 = QtWidgets.QLabel(self.page_8)
        self.label_11.setGeometry(QtCore.QRect(84, 127, 1600, 200))
        self.label_11.setMinimumSize(QtCore.QSize(1558, 200))
        self.label_11.setMaximumSize(QtCore.QSize(1600, 100))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/Images/Images/Paneles 1-10.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_4 = QtWidgets.QLabel(self.page_8)
        self.label_4.setGeometry(QtCore.QRect(198, 127, 138, 194))
        self.label_4.setMaximumSize(QtCore.QSize(481, 16777215))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Images/Images/A175000-Modulo_cerrado_2.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.close_2 = QtWidgets.QLabel(self.page_8)
        self.close_2.setGeometry(QtCore.QRect(335, 127, 138, 194))
        self.close_2.setMaximumSize(QtCore.QSize(481, 16777215))
        self.close_2.setText("")
        self.close_2.setPixmap(QtGui.QPixmap(":/Images/Images/A175000-Modulo_cerrado_2.png"))
        self.close_2.setScaledContents(True)
        self.close_2.setObjectName("close_2")
        self.close_3 = QtWidgets.QLabel(self.page_8)
        self.close_3.setGeometry(QtCore.QRect(470, 127, 138, 194))
        self.close_3.setMaximumSize(QtCore.QSize(481, 16777215))
        self.close_3.setText("")
        self.close_3.setPixmap(QtGui.QPixmap(":/Images/Images/A175000-Modulo_cerrado_2.png"))
        self.close_3.setScaledContents(True)
        self.close_3.setObjectName("close_3")
        self.close_4 = QtWidgets.QLabel(self.page_8)
        self.close_4.setGeometry(QtCore.QRect(606, 127, 138, 194))
        self.close_4.setMaximumSize(QtCore.QSize(481, 16777215))
        self.close_4.setText("")
        self.close_4.setPixmap(QtGui.QPixmap(":/Images/Images/A175000-Modulo_cerrado_2.png"))
        self.close_4.setScaledContents(True)
        self.close_4.setObjectName("close_4")
        self.close_5 = QtWidgets.QLabel(self.page_8)
        self.close_5.setGeometry(QtCore.QRect(744, 127, 138, 194))
        self.close_5.setMaximumSize(QtCore.QSize(481, 16777215))
        self.close_5.setText("")
        self.close_5.setPixmap(QtGui.QPixmap(":/Images/Images/A175000-Modulo_cerrado_2.png"))
        self.close_5.setScaledContents(True)
        self.close_5.setObjectName("close_5")
        self.close_6 = QtWidgets.QLabel(self.page_8)
        self.close_6.setGeometry(QtCore.QRect(882, 127, 138, 194))
        self.close_6.setMaximumSize(QtCore.QSize(481, 16777215))
        self.close_6.setText("")
        self.close_6.setPixmap(QtGui.QPixmap(":/Images/Images/A175000-Modulo_cerrado_2.png"))
        self.close_6.setScaledContents(True)
        self.close_6.setObjectName("close_6")
        self.close_7 = QtWidgets.QLabel(self.page_8)
        self.close_7.setGeometry(QtCore.QRect(1019, 127, 138, 194))
        self.close_7.setMaximumSize(QtCore.QSize(481, 16777215))
        self.close_7.setText("")
        self.close_7.setPixmap(QtGui.QPixmap(":/Images/Images/A175000-Modulo_cerrado_2.png"))
        self.close_7.setScaledContents(True)
        self.close_7.setObjectName("close_7")
        self.close_8 = QtWidgets.QLabel(self.page_8)
        self.close_8.setGeometry(QtCore.QRect(1155, 127, 138, 194))
        self.close_8.setMaximumSize(QtCore.QSize(481, 16777215))
        self.close_8.setText("")
        self.close_8.setPixmap(QtGui.QPixmap(":/Images/Images/A175000-Modulo_cerrado_2.png"))
        self.close_8.setScaledContents(True)
        self.close_8.setObjectName("close_8")
        self.close_9 = QtWidgets.QLabel(self.page_8)
        self.close_9.setGeometry(QtCore.QRect(1292, 127, 138, 194))
        self.close_9.setMaximumSize(QtCore.QSize(481, 16777215))
        self.close_9.setText("")
        self.close_9.setPixmap(QtGui.QPixmap(":/Images/Images/A175000-Modulo_cerrado_2.png"))
        self.close_9.setScaledContents(True)
        self.close_9.setObjectName("close_9")
        self.close_10 = QtWidgets.QLabel(self.page_8)
        self.close_10.setGeometry(QtCore.QRect(1430, 127, 138, 194))
        self.close_10.setMaximumSize(QtCore.QSize(481, 16777215))
        self.close_10.setText("")
        self.close_10.setPixmap(QtGui.QPixmap(":/Images/Images/A175000-Modulo_cerrado_2.png"))
        self.close_10.setScaledContents(True)
        self.close_10.setObjectName("close_10")
        self.frame_19 = QtWidgets.QFrame(self.page_8)
        self.frame_19.setGeometry(QtCore.QRect(190, 460, 1391, 381))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_17 = QtWidgets.QFrame(self.frame_19)
        self.frame_17.setStyleSheet("QPushButton#panel_1o{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_1o:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}\n"
"QPushButton#panel_1c{\n"
"    background-color: rgb(179, 35, 10);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_1c:pressed{\n"
"\n"
"\n"
"    background-color: rgb(255, 17, 0);\n"
"\n"
"}\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.panel_1c = QtWidgets.QPushButton(self.frame_17)
        self.panel_1c.setGeometry(QtCore.QRect(10, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_1c.setFont(font)
        self.panel_1c.setStyleSheet("QPushButton#panel_1{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_1:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}")
        self.panel_1c.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Images/icons/arrow-up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.panel_1c.setIcon(icon7)
        self.panel_1c.setIconSize(QtCore.QSize(70, 70))
        self.panel_1c.setObjectName("panel_1c")
        self.panel_1o = QtWidgets.QPushButton(self.frame_17)
        self.panel_1o.setGeometry(QtCore.QRect(10, 230, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_1o.setFont(font)
        self.panel_1o.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Images/icons/arrow-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.panel_1o.setIcon(icon8)
        self.panel_1o.setIconSize(QtCore.QSize(70, 70))
        self.panel_1o.setObjectName("panel_1o")
        self.horizontalLayout_15.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_19)
        self.frame_18.setStyleSheet("QPushButton#panel_2o{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_2o:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}\n"
"QPushButton#panel_2c{\n"
"    background-color: rgb(179, 35, 10);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_2c:pressed{\n"
"\n"
"\n"
"    background-color: rgb(255, 17, 0);\n"
"\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.panel_2c = QtWidgets.QPushButton(self.frame_18)
        self.panel_2c.setGeometry(QtCore.QRect(10, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_2c.setFont(font)
        self.panel_2c.setStyleSheet("QPushButton#panel_1{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_1:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}")
        self.panel_2c.setText("")
        self.panel_2c.setIcon(icon7)
        self.panel_2c.setIconSize(QtCore.QSize(70, 70))
        self.panel_2c.setObjectName("panel_2c")
        self.panel_2o = QtWidgets.QPushButton(self.frame_18)
        self.panel_2o.setGeometry(QtCore.QRect(10, 230, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_2o.setFont(font)
        self.panel_2o.setText("")
        self.panel_2o.setIcon(icon8)
        self.panel_2o.setIconSize(QtCore.QSize(70, 70))
        self.panel_2o.setObjectName("panel_2o")
        self.horizontalLayout_15.addWidget(self.frame_18)
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setStyleSheet("QPushButton#panel_3o{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_3o:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}\n"
"QPushButton#panel_3c{\n"
"    background-color: rgb(179, 35, 10);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_3c:pressed{\n"
"\n"
"\n"
"    background-color: rgb(255, 17, 0);\n"
"\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.panel_3c = QtWidgets.QPushButton(self.frame_20)
        self.panel_3c.setGeometry(QtCore.QRect(10, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_3c.setFont(font)
        self.panel_3c.setStyleSheet("QPushButton#panel_1{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_1:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}")
        self.panel_3c.setText("")
        self.panel_3c.setIcon(icon7)
        self.panel_3c.setIconSize(QtCore.QSize(70, 70))
        self.panel_3c.setObjectName("panel_3c")
        self.panel_3o = QtWidgets.QPushButton(self.frame_20)
        self.panel_3o.setGeometry(QtCore.QRect(10, 230, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_3o.setFont(font)
        self.panel_3o.setText("")
        self.panel_3o.setIcon(icon8)
        self.panel_3o.setIconSize(QtCore.QSize(70, 70))
        self.panel_3o.setObjectName("panel_3o")
        self.horizontalLayout_15.addWidget(self.frame_20)
        self.frame_22 = QtWidgets.QFrame(self.frame_19)
        self.frame_22.setStyleSheet("QPushButton#panel_4o{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_4o:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}\n"
"QPushButton#panel_4c{\n"
"    background-color: rgb(179, 35, 10);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_4c:pressed{\n"
"\n"
"\n"
"    background-color: rgb(255, 17, 0);\n"
"\n"
"}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.panel_4c = QtWidgets.QPushButton(self.frame_22)
        self.panel_4c.setGeometry(QtCore.QRect(10, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_4c.setFont(font)
        self.panel_4c.setStyleSheet("QPushButton#panel_1{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_1:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}")
        self.panel_4c.setText("")
        self.panel_4c.setIcon(icon7)
        self.panel_4c.setIconSize(QtCore.QSize(70, 70))
        self.panel_4c.setObjectName("panel_4c")
        self.panel_4o = QtWidgets.QPushButton(self.frame_22)
        self.panel_4o.setGeometry(QtCore.QRect(10, 230, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_4o.setFont(font)
        self.panel_4o.setText("")
        self.panel_4o.setIcon(icon8)
        self.panel_4o.setIconSize(QtCore.QSize(70, 70))
        self.panel_4o.setObjectName("panel_4o")
        self.horizontalLayout_15.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.frame_19)
        self.frame_23.setStyleSheet("QPushButton#panel_5o{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_5o:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}\n"
"QPushButton#panel_5c{\n"
"    background-color: rgb(179, 35, 10);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_5c:pressed{\n"
"\n"
"\n"
"    background-color: rgb(255, 17, 0);\n"
"\n"
"}\n"
"")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.panel_5c = QtWidgets.QPushButton(self.frame_23)
        self.panel_5c.setGeometry(QtCore.QRect(10, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_5c.setFont(font)
        self.panel_5c.setStyleSheet("QPushButton#panel_1{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_1:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}")
        self.panel_5c.setText("")
        self.panel_5c.setIcon(icon7)
        self.panel_5c.setIconSize(QtCore.QSize(70, 70))
        self.panel_5c.setObjectName("panel_5c")
        self.panel_5o = QtWidgets.QPushButton(self.frame_23)
        self.panel_5o.setGeometry(QtCore.QRect(10, 230, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_5o.setFont(font)
        self.panel_5o.setText("")
        self.panel_5o.setIcon(icon8)
        self.panel_5o.setIconSize(QtCore.QSize(70, 70))
        self.panel_5o.setObjectName("panel_5o")
        self.horizontalLayout_15.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.frame_19)
        self.frame_24.setStyleSheet("QPushButton#panel_6o{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_6o:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}\n"
"QPushButton#panel_6c{\n"
"    background-color: rgb(179, 35, 10);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_6c:pressed{\n"
"\n"
"\n"
"    background-color: rgb(255, 17, 0);\n"
"\n"
"}")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.panel_6c = QtWidgets.QPushButton(self.frame_24)
        self.panel_6c.setGeometry(QtCore.QRect(10, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_6c.setFont(font)
        self.panel_6c.setStyleSheet("QPushButton#panel_1{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_1:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}")
        self.panel_6c.setText("")
        self.panel_6c.setIcon(icon7)
        self.panel_6c.setIconSize(QtCore.QSize(70, 70))
        self.panel_6c.setObjectName("panel_6c")
        self.panel_6o = QtWidgets.QPushButton(self.frame_24)
        self.panel_6o.setGeometry(QtCore.QRect(10, 230, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_6o.setFont(font)
        self.panel_6o.setText("")
        self.panel_6o.setIcon(icon8)
        self.panel_6o.setIconSize(QtCore.QSize(70, 70))
        self.panel_6o.setObjectName("panel_6o")
        self.horizontalLayout_15.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.frame_19)
        self.frame_25.setStyleSheet("QPushButton#panel_7o{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_7o:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}\n"
"QPushButton#panel_7c{\n"
"    background-color: rgb(179, 35, 10);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_7c:pressed{\n"
"\n"
"\n"
"    background-color: rgb(255, 17, 0);\n"
"\n"
"}")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.panel_7c = QtWidgets.QPushButton(self.frame_25)
        self.panel_7c.setGeometry(QtCore.QRect(10, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_7c.setFont(font)
        self.panel_7c.setStyleSheet("QPushButton#panel_1{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_1:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}")
        self.panel_7c.setText("")
        self.panel_7c.setIcon(icon7)
        self.panel_7c.setIconSize(QtCore.QSize(70, 70))
        self.panel_7c.setObjectName("panel_7c")
        self.panel_7o = QtWidgets.QPushButton(self.frame_25)
        self.panel_7o.setGeometry(QtCore.QRect(10, 230, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_7o.setFont(font)
        self.panel_7o.setText("")
        self.panel_7o.setIcon(icon8)
        self.panel_7o.setIconSize(QtCore.QSize(70, 70))
        self.panel_7o.setObjectName("panel_7o")
        self.horizontalLayout_15.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.frame_19)
        self.frame_26.setStyleSheet("QPushButton#panel_8o{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_8o:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}\n"
"QPushButton#panel_8c{\n"
"    background-color: rgb(179, 35, 10);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_8c:pressed{\n"
"\n"
"\n"
"    background-color: rgb(255, 17, 0);\n"
"\n"
"}")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.panel_8c = QtWidgets.QPushButton(self.frame_26)
        self.panel_8c.setGeometry(QtCore.QRect(10, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_8c.setFont(font)
        self.panel_8c.setStyleSheet("QPushButton#panel_1{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_1:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}")
        self.panel_8c.setText("")
        self.panel_8c.setIcon(icon7)
        self.panel_8c.setIconSize(QtCore.QSize(70, 70))
        self.panel_8c.setObjectName("panel_8c")
        self.panel_8o = QtWidgets.QPushButton(self.frame_26)
        self.panel_8o.setGeometry(QtCore.QRect(10, 230, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_8o.setFont(font)
        self.panel_8o.setText("")
        self.panel_8o.setIcon(icon8)
        self.panel_8o.setIconSize(QtCore.QSize(70, 70))
        self.panel_8o.setObjectName("panel_8o")
        self.horizontalLayout_15.addWidget(self.frame_26)
        self.frame_27 = QtWidgets.QFrame(self.frame_19)
        self.frame_27.setStyleSheet("QPushButton#panel_9o{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_9o:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}\n"
"QPushButton#panel_9c{\n"
"    background-color: rgb(179, 35, 10);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_9c:pressed{\n"
"\n"
"\n"
"    background-color: rgb(255, 17, 0);\n"
"\n"
"}")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.panel_9c = QtWidgets.QPushButton(self.frame_27)
        self.panel_9c.setGeometry(QtCore.QRect(10, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_9c.setFont(font)
        self.panel_9c.setStyleSheet("QPushButton#panel_1{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_1:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}")
        self.panel_9c.setText("")
        self.panel_9c.setIcon(icon7)
        self.panel_9c.setIconSize(QtCore.QSize(70, 70))
        self.panel_9c.setObjectName("panel_9c")
        self.panel_9o = QtWidgets.QPushButton(self.frame_27)
        self.panel_9o.setGeometry(QtCore.QRect(10, 231, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_9o.setFont(font)
        self.panel_9o.setText("")
        self.panel_9o.setIcon(icon8)
        self.panel_9o.setIconSize(QtCore.QSize(70, 70))
        self.panel_9o.setObjectName("panel_9o")
        self.horizontalLayout_15.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.frame_19)
        self.frame_28.setStyleSheet("QPushButton#panel_10o{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_10o:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}\n"
"QPushButton#panel_10c{\n"
"    background-color: rgb(179, 35, 10);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_10c:pressed{\n"
"\n"
"\n"
"    background-color: rgb(255, 17, 0);\n"
"\n"
"}")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.panel_10c = QtWidgets.QPushButton(self.frame_28)
        self.panel_10c.setGeometry(QtCore.QRect(10, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_10c.setFont(font)
        self.panel_10c.setStyleSheet("QPushButton#panel_1{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#panel_1:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}")
        self.panel_10c.setText("")
        self.panel_10c.setIcon(icon7)
        self.panel_10c.setIconSize(QtCore.QSize(70, 70))
        self.panel_10c.setObjectName("panel_10c")
        self.panel_10o = QtWidgets.QPushButton(self.frame_28)
        self.panel_10o.setGeometry(QtCore.QRect(10, 231, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.panel_10o.setFont(font)
        self.panel_10o.setText("")
        self.panel_10o.setIcon(icon8)
        self.panel_10o.setIconSize(QtCore.QSize(70, 70))
        self.panel_10o.setObjectName("panel_10o")
        self.horizontalLayout_15.addWidget(self.frame_28)
        self.frame_29 = QtWidgets.QFrame(self.page_8)
        self.frame_29.setGeometry(QtCore.QRect(86, 320, 1592, 81))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.frame_16 = QtWidgets.QFrame(self.frame_29)
        self.frame_16.setGeometry(QtCore.QRect(160, 10, 1371, 51))
        self.frame_16.setStyleSheet("#num_1,#num_2,#num_3,#num_4,#num_5,#num_6,#num_7,#num_8,#num_9,#num_10{\n"
"    color:#000000;\n"
"\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.num_1 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.num_1.setFont(font)
        self.num_1.setObjectName("num_1")
        self.horizontalLayout_16.addWidget(self.num_1)
        self.num_2 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.num_2.setFont(font)
        self.num_2.setObjectName("num_2")
        self.horizontalLayout_16.addWidget(self.num_2)
        self.num_3 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.num_3.setFont(font)
        self.num_3.setObjectName("num_3")
        self.horizontalLayout_16.addWidget(self.num_3)
        self.num_4 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.num_4.setFont(font)
        self.num_4.setObjectName("num_4")
        self.horizontalLayout_16.addWidget(self.num_4)
        self.num_5 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.num_5.setFont(font)
        self.num_5.setObjectName("num_5")
        self.horizontalLayout_16.addWidget(self.num_5)
        self.num_6 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.num_6.setFont(font)
        self.num_6.setObjectName("num_6")
        self.horizontalLayout_16.addWidget(self.num_6)
        self.num_7 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.num_7.setFont(font)
        self.num_7.setObjectName("num_7")
        self.horizontalLayout_16.addWidget(self.num_7)
        self.num_8 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.num_8.setFont(font)
        self.num_8.setObjectName("num_8")
        self.horizontalLayout_16.addWidget(self.num_8)
        self.num_9 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.num_9.setFont(font)
        self.num_9.setObjectName("num_9")
        self.horizontalLayout_16.addWidget(self.num_9)
        self.num_10 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.num_10.setFont(font)
        self.num_10.setObjectName("num_10")
        self.horizontalLayout_16.addWidget(self.num_10)
        self.label_11.raise_()
        self.label_4.raise_()
        self.close_2.raise_()
        self.close_3.raise_()
        self.close_4.raise_()
        self.close_5.raise_()
        self.close_6.raise_()
        self.close_8.raise_()
        self.close_9.raise_()
        self.close_10.raise_()
        self.close_7.raise_()
        self.frame_19.raise_()
        self.frame_29.raise_()
        self.mainPages.addWidget(self.page_8)
        self.temperature_page = QtWidgets.QWidget()
        self.temperature_page.setObjectName("temperature_page")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.temperature_page)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_21 = QtWidgets.QFrame(self.temperature_page)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.label_26 = QtWidgets.QLabel(self.frame_21)
        self.label_26.setGeometry(QtCore.QRect(160, 310, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_21)
        self.label_27.setGeometry(QtCore.QRect(350, 310, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_21)
        self.label_28.setGeometry(QtCore.QRect(540, 310, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.FC1_1 = QtWidgets.QLabel(self.frame_21)
        self.FC1_1.setGeometry(QtCore.QRect(180, 420, 71, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.FC1_1.setFont(font)
        self.FC1_1.setObjectName("FC1_1")
        self.FC1_2 = QtWidgets.QLabel(self.frame_21)
        self.FC1_2.setGeometry(QtCore.QRect(180, 550, 71, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.FC1_2.setFont(font)
        self.FC1_2.setObjectName("FC1_2")
        self.verticalLayout_17.addWidget(self.frame_21)
        self.mainPages.addWidget(self.temperature_page)
        self.flow_page = QtWidgets.QWidget()
        self.flow_page.setObjectName("flow_page")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.flow_page)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.flow_graphic = QtWidgets.QGraphicsView(self.flow_page)
        self.flow_graphic.setObjectName("flow_graphic")
        self.verticalLayout_18.addWidget(self.flow_graphic)
        self.mainPages.addWidget(self.flow_page)
        self.humidity_page = QtWidgets.QWidget()
        self.humidity_page.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.humidity_page.setObjectName("humidity_page")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.humidity_page)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.humidity_graphic = QtWidgets.QGraphicsView(self.humidity_page)
        self.humidity_graphic.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.humidity_graphic.setSizeIncrement(QtCore.QSize(-1, 0))
        self.humidity_graphic.setObjectName("humidity_graphic")
        self.verticalLayout_19.addWidget(self.humidity_graphic)
        self.mainPages.addWidget(self.humidity_page)
        self.pressure_page = QtWidgets.QWidget()
        self.pressure_page.setObjectName("pressure_page")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.pressure_page)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.pressure_graphic = QtWidgets.QGraphicsView(self.pressure_page)
        self.pressure_graphic.setObjectName("pressure_graphic")
        self.verticalLayout_23.addWidget(self.pressure_graphic)
        self.mainPages.addWidget(self.pressure_page)
        self.flow_1 = QtWidgets.QWidget()
        self.flow_1.setObjectName("flow_1")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.flow_1)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.flow_1gl = QtWidgets.QOpenGLWidget(self.flow_1)
        self.flow_1gl.setObjectName("flow_1gl")
        self.verticalLayout_24.addWidget(self.flow_1gl)
        self.mainPages.addWidget(self.flow_1)
        self.flow_2 = QtWidgets.QWidget()
        self.flow_2.setObjectName("flow_2")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.flow_2)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.flow_2gl = QtWidgets.QOpenGLWidget(self.flow_2)
        self.flow_2gl.setObjectName("flow_2gl")
        self.verticalLayout_25.addWidget(self.flow_2gl)
        self.mainPages.addWidget(self.flow_2)
        self.energy_1 = QtWidgets.QWidget()
        self.energy_1.setObjectName("energy_1")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.energy_1)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.energy_1gl = QtWidgets.QOpenGLWidget(self.energy_1)
        self.energy_1gl.setObjectName("energy_1gl")
        self.verticalLayout_26.addWidget(self.energy_1gl)
        self.mainPages.addWidget(self.energy_1)
        self.energy_2 = QtWidgets.QWidget()
        self.energy_2.setObjectName("energy_2")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.energy_2)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.energy_2gl = QtWidgets.QOpenGLWidget(self.energy_2)
        self.energy_2gl.setObjectName("energy_2gl")
        self.verticalLayout_27.addWidget(self.energy_2gl)
        self.mainPages.addWidget(self.energy_2)
        self.verticalLayout_15.addWidget(self.mainPages)
        self.horizontalLayout_8.addWidget(self.mainContentsContainer)
        self.rightMenuContainer = QCustomSlideMenu(self.mainbodyContent)
        self.rightMenuContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.rightMenuContainer.setMaximumSize(QtCore.QSize(0, 0))
        self.rightMenuContainer.setObjectName("rightMenuContainer")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.rightMenuContainer)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.rightMenuSubContainer = QtWidgets.QWidget(self.rightMenuContainer)
        self.rightMenuSubContainer.setMinimumSize(QtCore.QSize(200, 500))
        self.rightMenuSubContainer.setMaximumSize(QtCore.QSize(0, 0))
        self.rightMenuSubContainer.setObjectName("rightMenuSubContainer")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.rightMenuSubContainer)
        self.verticalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_8 = QtWidgets.QFrame(self.rightMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.closeRightMenuBtn = QtWidgets.QPushButton(self.frame_8)
        self.closeRightMenuBtn.setText("")
        self.closeRightMenuBtn.setIcon(icon3)
        self.closeRightMenuBtn.setIconSize(QtCore.QSize(40, 40))
        self.closeRightMenuBtn.setObjectName("closeRightMenuBtn")
        self.horizontalLayout_9.addWidget(self.closeRightMenuBtn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_12.addWidget(self.frame_8)
        self.frame_13 = QtWidgets.QFrame(self.rightMenuSubContainer)
        self.frame_13.setStyleSheet("")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setStyleSheet("QPushButton#startBtn{\n"
"    \n"
"    background-color: rgb(0, 111, 37);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#startBtn:pressed{\n"
"\n"
"\n"
"    background-color: rgb(21, 202, 1);\n"
"\n"
"}\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.startBtn = QtWidgets.QPushButton(self.frame_14)
        self.startBtn.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.startBtn.setFont(font)
        self.startBtn.setStyleSheet("")
        self.startBtn.setIconSize(QtCore.QSize(16, 16))
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout_13.addWidget(self.startBtn)
        self.verticalLayout_16.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setStyleSheet("QPushButton#stopBtn{\n"
"    background-color: rgb(179, 35, 10);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#stopBtn:pressed{\n"
"\n"
"\n"
"    background-color: rgb(255, 17, 0);\n"
"\n"
"}\n"
"")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.stopBtn = QtWidgets.QPushButton(self.frame_15)
        self.stopBtn.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.stopBtn.setFont(font)
        self.stopBtn.setStyleSheet("")
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_14.addWidget(self.stopBtn)
        self.verticalLayout_16.addWidget(self.frame_15)
        self.verticalLayout_12.addWidget(self.frame_13)
        self.rightMenuPages = QCustomStackedWidget(self.rightMenuSubContainer)
        self.rightMenuPages.setObjectName("rightMenuPages")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_13.addWidget(self.label_8)
        self.rightMenuPages.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.page_5)
        self.label_10.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.frame_9 = QtWidgets.QFrame(self.page_5)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_20.addWidget(self.label_13)
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_20.addWidget(self.label_9)
        self.horizontalLayout_10.addWidget(self.frame_10)
        self.frame_12 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_17 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_22.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_22.addWidget(self.label_16)
        self.horizontalLayout_10.addWidget(self.frame_12)
        self.verticalLayout_14.addWidget(self.frame_9, 0, QtCore.Qt.AlignHCenter)
        self.rightMenuPages.addWidget(self.page_5)
        self.verticalLayout_12.addWidget(self.rightMenuPages, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_11.addWidget(self.rightMenuSubContainer)
        self.horizontalLayout_8.addWidget(self.rightMenuContainer, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.mainbodyContent)
        self.footeContainer = QtWidgets.QWidget(self.mainBodyContainer)
        self.footeContainer.setObjectName("footeContainer")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.footeContainer)
        self.horizontalLayout_11.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(7)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_11 = QtWidgets.QFrame(self.footeContainer)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_21.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_21.addWidget(self.label_15)
        self.horizontalLayout_11.addWidget(self.frame_11)
        self.sizeGrip = QtWidgets.QFrame(self.footeContainer)
        self.sizeGrip.setMinimumSize(QtCore.QSize(30, 30))
        self.sizeGrip.setMaximumSize(QtCore.QSize(40, 40))
        self.sizeGrip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sizeGrip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sizeGrip.setObjectName("sizeGrip")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.sizeGrip)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11.addWidget(self.sizeGrip)
        self.verticalLayout_10.addWidget(self.footeContainer)
        self.horizontalLayout.addWidget(self.mainBodyContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.centerMenuPages.setCurrentIndex(2)
        self.mainPages.setCurrentIndex(0)
        self.rightMenuPages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuBtn.setToolTip(_translate("MainWindow", "Menu"))
        self.homeBtn.setToolTip(_translate("MainWindow", "Home"))
        self.homeBtn.setText(_translate("MainWindow", "Panels"))
        self.dataBtn.setToolTip(_translate("MainWindow", "Data Analysis"))
        self.dataBtn.setText(_translate("MainWindow", "Information"))
        self.label.setText(_translate("MainWindow", "More Menu"))
        self.closeCenterMenuBtn.setToolTip(_translate("MainWindow", "Close Menu"))
        self.label_2.setText(_translate("MainWindow", "Settings"))
        self.label_3.setText(_translate("MainWindow", "Information"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-style:italic;\">If you need any other information or help, don\'t doubt to visit our website or contact with us.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-style:italic;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-style:italic;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-style:italic;\">Website:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-style:italic;\">( https://www.mequonic.com/ ) </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-style:italic;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-style:italic;\">Email:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-style:italic;\">(</span><a name=\"yui_3_17_2_1_1693328266162_199\"></a><span style=\" font-size:18pt; font-style:italic;\">c</span><span style=\" font-size:18pt; font-style:italic;\">ontact@mequonic.com )</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Proyecto: Paneles piscina"))
        self.minimizeBtn.setToolTip(_translate("MainWindow", "Minimize Window "))
        self.restoreBtn.setToolTip(_translate("MainWindow", "Restore Window"))
        self.closeBtn.setToolTip(_translate("MainWindow", "Close Window"))
        self.num_1.setText(_translate("MainWindow", "1"))
        self.num_2.setText(_translate("MainWindow", "2"))
        self.num_3.setText(_translate("MainWindow", "3"))
        self.num_4.setText(_translate("MainWindow", "4"))
        self.num_5.setText(_translate("MainWindow", "5"))
        self.num_6.setText(_translate("MainWindow", "6"))
        self.num_7.setText(_translate("MainWindow", "7"))
        self.num_8.setText(_translate("MainWindow", "8"))
        self.num_9.setText(_translate("MainWindow", "9"))
        self.num_10.setText(_translate("MainWindow", "10"))
        self.label_26.setText(_translate("MainWindow", "Piston 1"))
        self.label_27.setText(_translate("MainWindow", "Piston 2"))
        self.label_28.setText(_translate("MainWindow", "Piston 3"))
        self.FC1_1.setText(_translate("MainWindow", "F.C 1"))
        self.FC1_2.setText(_translate("MainWindow", "F.C 2"))
        self.label_7.setText(_translate("MainWindow", "Right Menu"))
        self.closeRightMenuBtn.setToolTip(_translate("MainWindow", "Close Menu"))
        self.startBtn.setText(_translate("MainWindow", "Start"))
        self.stopBtn.setText(_translate("MainWindow", "Stop"))
        self.label_8.setText(_translate("MainWindow", "Profile"))
        self.label_10.setText(_translate("MainWindow", "Position ( X, Y )"))
        self.label_13.setText(_translate("MainWindow", "( X ) AXIS"))
        self.label_9.setText(_translate("MainWindow", "( Y ) AXIS"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
from Custom_Widgets.Widgets import QCustomSlideMenu, QCustomStackedWidget
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
